cask_args appdir: "/Applications"
cask_args "no-quarantine": true

tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-versions"

# Mac App Store
mas "1Password", id: 1333542190

# Libraries
cask "google-cloud-sdk"
cask "adoptopenjdk"

# Communications apps
cask "slack"
cask "zoom"
cask "gpg-suite-no-mail"

# Dev tools
cask "visual-studio-code"
cask "docker"
cask "postico"
cask "insomnia"

# Other
cask "iina"
cask "transmission"
cask "webcatalog"
cask "plex"
cask "plexamp"
cask "google-chrome"

# Formulas
brew "awscli"
brew "coreutils"
brew "findutils"
brew "go"
brew "gnu-tar"
brew "gnu-sed"
brew "gawk"
brew "gnutls"
brew "openssl"
brew "node@14"
brew "tag"
brew "gh"
