cask_args appdir: "/Applications"
cask_args "no-quarantine": true

tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-versions"

# Mac App Store
mas "1Password", id: 1333542190
mas "AdBlock", id: 1402042596
mas "Messenger", id: 1480068668
mas "Meeter", id: 1510445899

# Libraries
cask "google-cloud-sdk"
cask "adoptopenjdk"

# Communications apps
cask "slack"
cask "discord"
cask "zoomus"
cask "gpg-suite"
cask "keybase"

# Dev tools
cask "visual-studio-code"
cask "docker"
cask "postico"
cask "insomnia"

# Other
cask "iina"
cask "transmission"
cask "webcatalog"
cask "plex"
cask "plexamp"
cask "google-chrome"

# Formulas
brew "awscli"
brew "coreutils"
brew "docker-clean"
brew "findutils"
brew "go"
brew "gnu-tar"
brew "gnu-sed"
brew "gawk"
brew "gnutls"
brew "openssl"
brew "unrar"
brew "dnsmasq"
brew "hub"
brew "node"
