cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'homebrew/science'
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'mshick/personal'

cask 'xquartz'
cask 'atom'
cask 'firefox'
brew 'google-chrome'
cask 'handbrake'
cask 'slack'
cask 'vlc'
cask 'font-source-code-pro'
cask 'rightfont'
cask 'bittorrent-sync'
cask 'cyberduck'
cask 'screenhero'
cask 'google-play-music-desktop-player'
cask 'flux'
cask 'dropbox'
cask 'ginbox'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'nvm'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spark'
brew 'unrar'
brew 'youtube-dl'
brew 'dnsmasq'
brew 'hub'
brew 'tmux'
brew 'z'
brew 'zsh-syntax-highlighting'
brew 'zsh-history-substring-search'
