#!/usr/bin/env bash
#
# bootstrap installs things.

export PATH=/usr/local/bin:$PATH

cd "$(dirname "$0")/.."
DOTFILES=$(pwd)

set -e

echo ''

source "$DOTFILES/util/interactive"

setup_gitconfig () {
  if ! [ -f "$DOTFILES/../.gitconfig.local" ]
  then
    info 'setup gitconfig'

    git_credential='osxkeychain'

    user ' - What is your github username?'
    read -e git_username
    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail
    user ' - What is your GPG signing key?'
    read -e git_signingkey

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/USERNAME/$git_username/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" -e "s/SIGNINGKEY/$git_signingkey/g" git/gitconfig.local.example > "$DOTFILES/../.gitconfig.local"
    mkdir -p $DOTFILES/../.config && touch $DOTFILES/../.config/hub && sed -e "s/AUTHORNAME/$git_authorname/g" config/hub.example > "$DOTFILES/../.config/hub"

    success 'gitconfig'
  fi
}

install_zim () {
    info 'installing ZIM before everything else'
    sh -c "$DOTFILES/zsh/install.sh"
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES" -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_gitconfig
install_zim
install_dotfiles

# If we're on a Mac, do continue the package install
echo "All set. Now run ./script/install"
