#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

export ZSH=$HOME/.dotfiles

# Install Homebrew
$ZSH/homebrew/install.sh 2>&1

# Upgrade Homebrew
echo "› brew update"
brew update

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
find $ZSH -name install.sh | while read installer ; do sh -c "${installer}" ; done

# Set OS X defaults
$ZSH/macos/set-defaults.sh
