#!/usr/bin/env bash

set -e

# Install Homebrew
# It's needed everywhere...
if test ! $(which brew)
then
  echo "  Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > /tmp/homebrew-install.log
fi

# Run all dotfiles installers.
cd "$(dirname $0)"/..
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
