#!/usr/bin/env bash
#
# Run all dotfiles installers.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

export DOTFILES=$HOME/.dotfiles

# Install Homebrew
$DOTFILES/homebrew/install.sh 2>&1

# Upgrade Homebrew
echo "› brew update"
brew update

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
set -e

find $DOTFILES -name install.sh | while read installer ; do sh -c "${installer}" ; done

# Set OS X defaults
$DOTFILES/macos/set-defaults.sh

echo "Done installing!"