cask_args appdir: "/Applications"
cask_args "no-quarantine": true

tap "homebrew/bundle"
tap "homebrew/services"

# Mac App Store
mas "1Password", id: 1333542190

# Applications
cask "plex-media-server"
cask "plex"

# Formulas
brew "coreutils"
brew "findutils"
brew "gnu-tar"
brew "gnu-sed"
brew "gawk"
brew "gnutls"
brew "openssl"
brew "unrar"
brew "dnsmasq"
brew "hub"
brew "node"
brew "ffmpeg"
brew "atomicparsley"
brew "ddclient"
brew "nginx"
brew "transmission-cli"
brew "watchman"
